# Generated by Django 4.2.2 on 2023-08-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='directions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='dolzhnost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dolzhnost', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='goroda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorod', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='standart_motivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorod', models.CharField(max_length=80)),
                ('dolzhnost', models.CharField(max_length=80)),
                ('oklad', models.CharField(max_length=50)),
                ('percent_of_sales', models.CharField(max_length=50)),
                ('premia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='zarplata_elements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorod', models.CharField(max_length=80)),
                ('dolzhnost', models.CharField(max_length=80)),
                ('direction', models.CharField(max_length=80)),
                ('oklad_type_motivation', models.CharField(max_length=50)),
                ('percent_of_sales_type_motivation', models.CharField(max_length=50)),
                ('premia_type_motivation', models.CharField(max_length=50)),
            ],
        ),
    ]
