# Generated by Django 4.2 on 2023-08-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_symbols_for_tabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='standart_motivation',
            name='direction',
            field=models.CharField(default='default', max_length=80),
        ),
    ]
