# Generated by Django 4.2.2 on 2023-08-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_standart_motivation_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='zarplata_list_elements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zp_element', models.CharField(max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='standart_motivation',
            name='oklad',
        ),
        migrations.RemoveField(
            model_name='standart_motivation',
            name='percent_of_sales',
        ),
        migrations.RemoveField(
            model_name='standart_motivation',
            name='premia',
        ),
        migrations.RemoveField(
            model_name='zarplata_elements',
            name='oklad_type_motivation',
        ),
        migrations.RemoveField(
            model_name='zarplata_elements',
            name='percent_of_sales_type_motivation',
        ),
        migrations.RemoveField(
            model_name='zarplata_elements',
            name='premia_type_motivation',
        ),
        migrations.AddField(
            model_name='standart_motivation',
            name='element_motivation',
            field=models.CharField(default='Оклад', max_length=80),
        ),
        migrations.AddField(
            model_name='standart_motivation',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zarplata_elements',
            name='type_motivation',
            field=models.CharField(default='Стандарт', max_length=80),
        ),
        migrations.AddField(
            model_name='zarplata_elements',
            name='zazrplata_element',
            field=models.CharField(default='Оклад', max_length=80),
        ),
    ]
