# Generated by Django 4.2.2 on 2023-08-09 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_zarplata_list_elements_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zarplata_elements',
            old_name='zazrplata_element',
            new_name='zarplata_element',
        ),
    ]
