# Generated by Django 4.2 on 2023-08-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_rename_zazrplata_element_zarplata_elements_zarplata_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standart_motivation',
            name='direction',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='standart_motivation',
            name='element_motivation',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='zarplata_elements',
            name='type_motivation',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='zarplata_elements',
            name='zarplata_element',
            field=models.CharField(max_length=80),
        ),
    ]
