# Generated by Django 4.2.2 on 2023-08-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_standart_motivation_direction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('holiday_name', models.CharField(max_length=80)),
            ],
        ),
    ]
