# Generated by Django 4.2.2 on 2023-08-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_holidays'),
    ]

    operations = [
        migrations.CreateModel(
            name='permissions_goroda_and_directions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('gorod', models.CharField(max_length=80)),
                ('direction', models.CharField(max_length=80)),
            ],
        ),
    ]
