# Generated by Django 4.2.2 on 2023-08-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_permissions_goroda_and_directions'),
    ]

    operations = [
        migrations.CreateModel(
            name='types_motivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_motivation', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='standart_motivation',
            name='value',
            field=models.IntegerField(),
        ),
    ]
