# Generated by Django 4.2 on 2023-08-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_types_motivation_alter_standart_motivation_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_client', models.CharField(max_length=80)),
            ],
        ),
    ]
