# Generated by Django 4.2.2 on 2023-08-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='files_types_for_raschet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=80)),
            ],
        ),
    ]
