# Generated by Django 4.2.2 on 2023-08-18 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_files_types_for_raschet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goroda',
            options={'ordering': ['gorod']},
        ),
    ]
