# Generated by Django 4.2.2 on 2023-08-18 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_alter_goroda_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'ordering': ['name_client']},
        ),
        migrations.AlterModelOptions(
            name='directions',
            options={'ordering': ['direction']},
        ),
        migrations.AlterModelOptions(
            name='dolzhnost',
            options={'ordering': ['dolzhnost']},
        ),
        migrations.AlterModelOptions(
            name='files_types_for_raschet',
            options={'ordering': ['file_type']},
        ),
        migrations.AlterModelOptions(
            name='types_motivation',
            options={'ordering': ['type_motivation']},
        ),
        migrations.AlterModelOptions(
            name='zarplata_list_elements',
            options={'ordering': ['zp_element']},
        ),
    ]
