# Generated by Django 4.2.2 on 2023-08-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_alter_clients_options_alter_directions_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tags_to_types_for_realization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=80)),
                ('type_sale', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['tag'],
            },
        ),
    ]
