# Generated by Django 4.2.2 on 2023-08-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_tags_to_types_for_realization'),
    ]

    operations = [
        migrations.CreateModel(
            name='permissions_for_urls_grops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(max_length=80)),
                ('name_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='permissions_for_urls_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=80)),
                ('name_url', models.TextField()),
            ],
        ),
    ]
