# Generated by Django 4.2.2 on 2023-08-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_permissions_for_urls_grops_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='names_sections_and_urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_section', models.CharField(max_length=80)),
                ('name_url', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='permissions_for_urls_grops',
            name='name_url',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='permissions_for_urls_users',
            name='name_url',
            field=models.CharField(max_length=80),
        ),
    ]
