# Generated by Django 4.2.2 on 2023-08-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_names_sections_and_urls_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='permissions_for_urls_grops',
            new_name='permissions_for_urls_groups',
        ),
    ]
