# Generated by Django 4.2.2 on 2023-08-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0017_rename_permissions_for_urls_grops_permissions_for_urls_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions_for_urls_groups',
            name='name_section',
            field=models.CharField(default='Главная', max_length=80),
        ),
        migrations.AddField(
            model_name='permissions_for_urls_users',
            name='name_section',
            field=models.CharField(default='Главная', max_length=80),
        ),
        migrations.AlterField(
            model_name='names_sections_and_urls',
            name='name_section',
            field=models.CharField(default='Главная', max_length=80),
        ),
    ]
