# Generated by Django 4.2.2 on 2023-08-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0018_permissions_for_urls_groups_name_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='names_sections_and_urls',
            name='name_section',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='permissions_for_urls_groups',
            name='name_section',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='permissions_for_urls_users',
            name='name_section',
            field=models.CharField(max_length=80),
        ),
    ]
