# Generated by Django 4.2.2 on 2023-09-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0020_remove_names_sections_and_urls_name_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='radio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['radio'],
            },
        ),
        migrations.DeleteModel(
            name='clients',
        ),
        migrations.DeleteModel(
            name='directions',
        ),
        migrations.DeleteModel(
            name='dolzhnost',
        ),
        migrations.DeleteModel(
            name='files_types_for_raschet',
        ),
        migrations.DeleteModel(
            name='standart_motivation',
        ),
        migrations.DeleteModel(
            name='symbols_for_tabel',
        ),
        migrations.DeleteModel(
            name='tags_to_types_for_realization',
        ),
        migrations.DeleteModel(
            name='types_motivation',
        ),
        migrations.DeleteModel(
            name='zarplata_elements',
        ),
        migrations.DeleteModel(
            name='zarplata_list_elements',
        ),
    ]
