# Generated by Django 4.2.2 on 2023-09-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0021_radio_delete_clients_delete_directions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='goroda_and_radio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorod', models.CharField(max_length=80)),
                ('radio', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['gorod'],
            },
        ),
    ]
