# Generated by Django 4.2.2 on 2023-09-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0023_weather_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather_calendar',
            name='date',
        ),
        migrations.AddField(
            model_name='weather_calendar',
            name='day',
            field=models.CharField(default='10', max_length=2),
        ),
        migrations.AddField(
            model_name='weather_calendar',
            name='month',
            field=models.CharField(default='10', max_length=2),
        ),
        migrations.AddField(
            model_name='weather_calendar',
            name='year',
            field=models.CharField(default='1000', max_length=4),
        ),
    ]
