# Generated by Django 4.2.2 on 2023-09-12 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0024_remove_weather_calendar_date_weather_calendar_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_calendar',
            name='day',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='weather_calendar',
            name='gorod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.goroda'),
        ),
        migrations.AlterField(
            model_name='weather_calendar',
            name='month',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='weather_calendar',
            name='radio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.radio'),
        ),
        migrations.AlterField(
            model_name='weather_calendar',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
