# Generated by Django 4.2.2 on 2023-09-12 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0026_rename_gorod_weather_calendar_gorod_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='weather_calendar',
        ),
    ]
