# Generated by Django 4.2.2 on 2023-09-12 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0027_delete_weather_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='weather_calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=2)),
                ('day', models.CharField(max_length=2)),
                ('status_weather', models.BooleanField()),
                ('gorod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.goroda')),
                ('radio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.radio')),
            ],
        ),
    ]
