# Generated by Django 4.2.2 on 2023-09-12 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0028_weather_calendar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goroda_and_radio',
            options={},
        ),
        migrations.RenameField(
            model_name='goroda_and_radio',
            old_name='gorod',
            new_name='gorod_id',
        ),
        migrations.RenameField(
            model_name='goroda_and_radio',
            old_name='radio',
            new_name='radio_id',
        ),
    ]
