# Generated by Django 4.2.2 on 2023-09-12 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0029_alter_goroda_and_radio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goroda_and_radio',
            name='gorod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.goroda'),
        ),
        migrations.AlterField(
            model_name='goroda_and_radio',
            name='radio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.radio'),
        ),
    ]
