# Generated by Django 4.2.2 on 2023-09-12 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0030_alter_goroda_and_radio_gorod_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather_calendar',
            old_name='gorod_id',
            new_name='gorod',
        ),
        migrations.RenameField(
            model_name='weather_calendar',
            old_name='radio_id',
            new_name='radio',
        ),
    ]
