# Generated by Django 4.2.2 on 2023-09-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0031_rename_gorod_id_weather_calendar_gorod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goroda_and_radio',
            name='gorod_id',
        ),
        migrations.RemoveField(
            model_name='goroda_and_radio',
            name='radio_id',
        ),
        migrations.AddField(
            model_name='goroda_and_radio',
            name='gorod',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goroda_and_radio',
            name='radio',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weather_calendar',
            name='gorod',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='weather_calendar',
            name='radio',
            field=models.CharField(max_length=80),
        ),
    ]
