# Generated by Django 4.2.2 on 2023-09-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0033_constant_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='goroda',
            name='gorod_in_yandex_weather',
            field=models.CharField(default='жопа', max_length=80),
        ),
    ]
