# Generated by Django 4.2 on 2023-09-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0034_goroda_gorod_in_yandex_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='radio_on_station',
            field=models.CharField(default='жопа', max_length=80),
        ),
        migrations.AlterField(
            model_name='goroda',
            name='gorod_in_yandex_weather',
            field=models.CharField(max_length=80),
        ),
    ]
