# Generated by Django 4.2.2 on 2023-10-26 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0035_radio_radio_on_station_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constant_weather',
            options={'ordering': ['gorod']},
        ),
    ]
