# Generated by Django 4.2.2 on 2023-11-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0036_alter_constant_weather_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='goroda',
            name='gorod_on_station',
            field=models.CharField(default='жопа', max_length=80),
        ),
    ]
