# Generated by Django 4.2 on 2025-01-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0037_goroda_gorod_on_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='goroda',
            name='gorod_id_yandex_weather',
            field=models.CharField(default='000', max_length=3),
        ),
        migrations.AlterField(
            model_name='goroda',
            name='gorod_on_station',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='radio',
            name='radio_on_station',
            field=models.CharField(default='default', max_length=80),
        ),
    ]
