# Generated by Django 4.2 on 2025-01-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0038_goroda_gorod_id_yandex_weather_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goroda',
            name='gorod_lat_and_lon',
            field=models.CharField(default='000', max_length=100),
        ),
    ]
