# Generated by Django 4.2 on 2025-02-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0039_goroda_gorod_lat_and_lon'),
    ]

    operations = [
        migrations.CreateModel(
            name='composite_weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorod', models.CharField(max_length=80)),
                ('radio', models.CharField(max_length=80)),
                ('list_goroda_additionally', models.TextField()),
            ],
            options={
                'ordering': ['gorod'],
            },
        ),
        migrations.CreateModel(
            name='goroda_paramtres_weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorod', models.CharField(max_length=80)),
                ('list_parametres_weather', models.TextField()),
            ],
            options={
                'ordering': ['gorod'],
            },
        ),
        migrations.CreateModel(
            name='parameters_weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_weather', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['parameter_weather'],
            },
        ),
    ]
