# Generated by Django 4.2 on 2025-02-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0040_composite_weather_goroda_paramtres_weather_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='goroda_additionally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorod', models.CharField(max_length=80)),
                ('gorod_in_yandex_weather', models.CharField(max_length=80)),
                ('gorod_id_yandex_weather', models.CharField(default='000', max_length=3)),
                ('gorod_lat_and_lon', models.CharField(default='000', max_length=100)),
            ],
            options={
                'ordering': ['gorod'],
            },
        ),
    ]
